## 00.Tensor_Manipulation

In [3]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

torch.__version__

'2.3.1+cu121'

### random, zeros, ones

In [ ]:
random_tensor = torch.rand(size = (3, 4))
random_image_tensor = torch.rand(size = (224, 224, 3))

In [ ]:
zeros = torch.zeros(size = (3, 4))
torch.ones(size = (3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### arange, zeros_like (shape as tensor)

In [ ]:
t1 = torch.arange(1, 11, step = .3) # exclude the end, [start, end), increment by step
t1

tensor([ 1.0000,  1.3000,  1.6000,  1.9000,  2.2000,  2.5000,  2.8000,  3.1000,
         3.4000,  3.7000,  4.0000,  4.3000,  4.6000,  4.9000,  5.2000,  5.5000,
         5.8000,  6.1000,  6.4000,  6.7000,  7.0000,  7.3000,  7.6000,  7.9000,
         8.2000,  8.5000,  8.8000,  9.1000,  9.4000,  9.7000, 10.0000, 10.3000,
        10.6000, 10.9000])

In [ ]:
torch.zeros_like(t1) # zeros shape same as t1

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### tensor attribute (dtype, device, requires_grad)

1. default is dtype = float32
2. two tensors multiply, higher precision is kept
3. float datatype overwrites integer data type

In [ ]:
float_64_tensor = torch.tensor([1.0, 2.0, 3.0],
                                dtype = torch.float64, # the data type, look up documentation
                                device = "cpu", # gpu(cuda) or cpu, tensors need to be on the same device to work
                                requires_grad = False) # whether or not to track gradients


float_64_tensor

tensor([1., 2., 3.])

### Get attributes from tensor

In [ ]:
some_tensor = torch.rand(size = (3, 4, 5))
some_tensor

tensor([[[0.9226, 0.3005, 0.0019, 0.0672, 0.3075],
         [0.8839, 0.0743, 0.8181, 0.0473, 0.8347],
         [0.1391, 0.3036, 0.9073, 0.0926, 0.9561],
         [0.7940, 0.2184, 0.3599, 0.9754, 0.8536]],

        [[0.9655, 0.8988, 0.7291, 0.1954, 0.5512],
         [0.2160, 0.7021, 0.1976, 0.7016, 0.3049],
         [0.9982, 0.4925, 0.9862, 0.9211, 0.9432],
         [0.6290, 0.2616, 0.1346, 0.1451, 0.1777]],

        [[0.4296, 0.1833, 0.6196, 0.6831, 0.9855],
         [0.6481, 0.5862, 0.1174, 0.4006, 0.2222],
         [0.1758, 0.1713, 0.4429, 0.1762, 0.5193],
         [0.4682, 0.7698, 0.1015, 0.4548, 0.0976]]])

In [ ]:
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

torch.float32
torch.Size([3, 4, 5])
cpu


### torch.matmul (alias torch.mm)

In [ ]:
a = torch.rand(size = (3, 4))
b = torch.rand(size = (4, 5))
torch.matmul(a, b)

tensor([[0.8972, 1.4593, 0.8286, 1.7956, 1.5744],
        [1.0929, 1.3170, 1.1320, 1.7830, 1.3549],
        [0.8463, 1.1425, 0.8470, 1.6118, 1.3994]])

In [ ]:
c = torch.rand(5, 4) # if shape does not match, use transpose for operation
torch.mm(a, c.T)

tensor([[0.7909, 1.8649, 1.0776, 0.9879, 1.4204],
        [0.5095, 1.8654, 0.9369, 1.3859, 1.5204],
        [0.5772, 1.6864, 0.9935, 1.1245, 1.3226]])

### tensor aggregation (min, max, mean, sum)

In [ ]:
a = torch.arange(0, 100, 10)
a = a.type(torch.float32)

In [ ]:
# a is torch.int64, one needs to convert to float32 to let mean work
a.max(), a.min(), a.type(torch.float32).mean(),a.sum()

(tensor(90.), tensor(0.), tensor(45.), tensor(450.))

In [ ]:
# return index position
# flatten, and return the max index
a.argmin(), a.argmax()

(tensor(0), tensor(9))

### reshape, stack, squeeze, unsqueeze, permute

In [10]:
x = torch.arange(1., 10.)
x = x.reshape(shape = (3, 3))

In [11]:
torch.stack([x, x, x, x], dim = 0) # 4*3*3, 0th position
torch.stack([x, x, x, x], dim = 1) # 3*4*3, 1th position
torch.stack([x, x, x, x], dim = 1) # 3*3*4, 2th
# break up at the dimth position, bring them all together

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]],

        [[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]],

        [[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]],

        [[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [15]:
y = torch.rand(size = (3,1,4))
y.squeeze() # A×1×B×C×1×D to A×B×C×D
y.squeeze(dim = 1) # reduce the dim'th "1" column

tensor([[0.3018, 0.5856, 0.5357, 0.2740],
        [0.5522, 0.7578, 0.7831, 0.9758],
        [0.5112, 0.2332, 0.9024, 0.7414]])

In [19]:
torch.unsqueeze(x, dim = 0)
torch.unsqueeze(x, dim = 1) # add 1 dimension at the dimth position
torch.unsqueeze(x, dim = 2)

tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]],

        [[7.],
         [8.],
         [9.]]])

In [25]:
# permute: rearrange in a specific order; shift axis 2->0, 0->1, 1->2
x = torch.rand(size = (224, 224, 3))
x_permuted = x.permute(2, 0, 1)
x_permuted.shape

torch.Size([3, 224, 224])

### resize: when there is only one column, it will collide into one row; shapes preserve

In [81]:
torch.rand(size = (3, 3))[:, 1:]

tensor([[0.2357, 0.1450],
        [0.3936, 0.1422],
        [0.5293, 0.3415]])

In [82]:
torch.rand(size = (3, 3))[:, 1] # 3*1 collides into a 1*3 row

tensor([0.6567, 0.4464, 0.8387])

In [83]:
x = torch.arange(1, 10).reshape(1, 3, 3)

### numpy to/from torch

In [87]:
arr = np.arange(1.0, 8.0)
torch.from_numpy(arr)

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [89]:
x = torch.arange(1.0, 8.0)
x.numpy()

array([1., 2., 3., 4., 5., 6., 7.], dtype=float32)

### manual_seed

In [94]:
torch.manual_seed(42)
c = torch.rand(3, 3)
torch.manual_seed(42)
d = torch.rand(3, 3)

In [95]:
c == d

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

### TPU Set Up (on cloud, need to install torch_xla for TPU driver)

In [8]:
import torch
import torch_xla.core.xla_model as xm

dev = xm.xla_device()
torch.device(dev)
t1 = torch.randn(3,3)
t2 = torch.randn(3,3)
print(t1 + t2)

tensor([[ 0.6969, -3.2214, -2.5050],
        [ 0.3762, -1.7805,  1.3698],
        [-1.4059,  0.9011,  0.4062]])


### GPU access
1. use colab default
2. run locally with Jupyter and local GPU
3. connect PyTorch to cloud computing devices

cuda (GPU driver): software programming API model for using GPUs for general processing purposes

In [4]:
torch.cuda.is_available()

True

In [5]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [6]:
torch.cuda.device_count()

1

### move tensors to gpu

In [9]:
tensor = torch.tensor([1, 2, 3])
tensor.device

device(type='cpu')

In [11]:
# move tensor to gpu
gpu_tensor = tensor.to('cuda')
gpu_tensor

tensor([1, 2, 3], device='cuda:0')

In [13]:
# numpy only works with cpu, thus it needs to be on cpu
gpu_tensor.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [14]:
gpu_tensor.to('cpu').numpy()

array([1, 2, 3])